[GLOBAL]
pants_version = "2.8.0rc5"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.black",
]

[python-infer]
string_imports = true

[flake8]
args=[
  "--max-line-length=120"
]
